export enum RouteEnum {
  HOME = "/",
  REGISTER = "/register",
  LOGIN = "/login",
  FORGOT_PASSWORD = "/forgot-password",
  SETTINGS = "/settings",
  FRIEND = "/friends",
  NOTIFICATION = "/notifications",
  All_FRIEND = "all-friends",
  SENT_REQUEST = "sent-request",
  FRIEND_REQUEST = "friend-request",
  ADMIN = "/admin",
  CONVERSATION = "/conversation",
  PROFILE = "/profile/:id",
  CREATE_POST = "create-post",
  POST = "/posts",
  GLOBAL_CHAT = "/global-chat",
}
